{% set name = "openfst" %}
{% set version = "1.7.5" %}

package: 
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.openfst.org/twiki/pub/FST/FstDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 85031ee2052dcc7c4f2f7d224599ba6467481168e36df515edd44aa4fa6de0de
  
build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - zlib

test:
  # If behaving properly these will have return code 1.
  commands:
    - fstinfo --helpshort >/dev/null || [[ $? == 1 ]]
    - fstcompress --helpshort >/dev/null || [[ $? == 1 ]]
    - farinfo --helpshort >/dev/null || [[ $? == 1 ]]
    - fstspecial --helpshort >/dev/null || [[ $? == 1 ]]
    - mpdtcompose --helpshort >/dev/null || [[ $? == 1 ]]
    - pdtcompose --helpshort >/dev/null || [[ $? == 1 ]]

about:
  home: http://openfst.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Weighted finite-state transducers
  description: |
    A library for constructing, combining, optimizing, and searching weighted 
    finite-state transducers (FSTs)
  doc_url: http://www.openfst.org/twiki/bin/view/FST/FstQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
