travis:
  secure:
    BINSTAR_TOKEN: OHCIld0sld7izH5C8Pl3uG/fVrKeonBl0VzUFAD9VMpNzrDTKRnBytiB3npob7KS9xTRF7JinVp72gECiIzPykRN9stGNB7woRReo/lFZjXwQf+X6V5QAE4hiD/h0q5rzy5buNL7ySR/5fjCKkSBYoBrei3kchN8zLUIo7gbtjItQd4Ca/wxukfNJ+wXvoQSlWykRBGFMA4bV9GC6QFtzc92y0B7PTLuuWNnQS/RGuOrgf5s2EMVZRhEQnebf+pMv5K9rVDQ2weMVToHbgo+FED/mwd+9oHhAXBGqZl93A0jEcjhV2Qf/GpHUdfq3hMYjxKLPJ+ALA4mfSqKrkdC5xN0Q4tzUOBxZtjDeX3jdf52Ix8W2qBZxus8BlYOCVDwCFq2AqGC5W9nCO5LbC2Vm8am5yzH5EtaxmNAcwDU2rwXA6gJ6E595uTTqS3IktT5TQH2yQmbiWtxtRjVef7QTdUhY0buqN/4S0N7axgkMgc+fETmwqWhZVKTechk+7Z1Gxvnlm3E48s1yO1F95mgaOG5XV3B3kjG5jOKVBr5R7cSO360LxnwRQPiZwwyiQ7xKBxtC8LzLsb1gptq5Pu3l4aIhdBoMrTYul0/yPLdvf4BvqCv37MLRIqlczT310qKJVdrOuPCq/rhUmmyyfQ1xGR2OA1ztbCfQSUWbz0RYS0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
