travis:
  secure:
    BINSTAR_TOKEN: Sv+dWFlo1qvFSyFEXXxhlmPzH7WqhD33c+GQ/UIv9WgIa6uGBADLncpK4McXBD9j4j+MsOLABhAGLtif5zyOkyU5GP8faoAQxAJj1oItPsAoUaD95bfWxE3yI4TQzv3Y0hoxFfpKcn4djEP2mLUA5GV5TjYhghT41Pq7Gsg7EGeaFytj8qD/HKqpMk5XT6XfCFGH/4REfSYYr6zciq0qpbqiiZZPk0j4Ele4hcnMPIm9VFkKOVO2wCJgQDsihXvJtkvYiaiv0B0s+dTTG/28JEz5rm2kIaUwgErVLzAB4Gm0k3I8HR2PjiAJHB51QEAHxp/07RrN/swMYSxUgIr9BzkUDlfiVQEIyFSxW37aKiMg12vfBYps2BJtnICLVRIoaKdb2qtJi/c0KOl1J1U+G9Y8JZ20VnhPeaR3EeV0FOLwp2MIBZcMdjm3dBEillmS3sDrEDzU+fvteF2cPmvhyE3FSAvZt3G4/oWqka6nuUUwg4HF5m32kmrL7R+nef37kohvIXCYUqw0GcoV6q9CzOxlJYtiBQOFnKl7cu1l8l0IpEZW8DFG22pMUv4+yxPAaucggATjgNzzXfqofAAkP/z409mjGnV7h9Xa6bLzRyhtaej/hNuKYsgK6kdw8p/ADYN6swOw4ZAYZSeTyEw88c4v6Yv8YY8fFXy2pWy4T4I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
